annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - HomeAutomation
    - Productivity
apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.0.9
deprecated: false
description: Enjoy Superslicer directly in your browser with this easy to use Chart Chart.
home: https://truecharts.org/charts/stable/prusaslicer-novnc
icon: https://truecharts.org/img/hotlink-ok/chart-icons/prusaslicer-novnc.png
keywords:
  - superslicer-novnc
  - HomeAutomation
  - Productivity
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: superslicer-novnc
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/prusaslicer-novnc
  - https://www.prusa3d.com/prusaslicer/
  - https://hub.docker.com/r/mikeah/superslicer-novnc
type: application
version: 3.0.4
